basePath: /
definitions:
  request.AddCarRequest:
    properties:
      carId:
        type: string
      garageId:
        type: string
    type: object
  request.CarRequest:
    properties:
      carId:
        type: string
    type: object
  request.CarUpgradesRequest:
    properties:
      carId:
        type: string
      paymentMode:
        type: string
    type: object
  request.GarageRequest:
    properties:
      carId:
        type: string
    type: object
  request.GuestLoginRequest:
    properties:
      deviceId:
        type: string
      os:
        type: integer
      playerName:
        type: string
      token:
        type: string
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
    type: object
  request.UpdateEmailRequest:
    properties:
      email:
        type: string
    type: object
  response.Success:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: This is the doumentation for drag racing game
  title: Drag Racing
  version: "2.0"
paths:
  /add-car-garage:
    post:
      consumes:
      - application/json
      description: Add a car to a player's garage
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add Car Request
        in: body
        name: addCarRequest
        required: true
        schema:
          $ref: '#/definitions/request.AddCarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Car added to garage successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Add Car to Garage
      tags:
      - Garage
  /buy-car:
    post:
      consumes:
      - application/json
      description: Buy a car for a player
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Buy Car Request
        in: body
        name: carRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Car added to player successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Car not found
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      security:
      - ApiKeyAuth: []
      summary: Buy Car
      tags:
      - Car
  /buy-garage:
    post:
      consumes:
      - application/json
      description: Buy a garage for a player
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Buy Garage Request
        in: body
        name: buyRequest
        required: true
        schema:
          $ref: '#/definitions/request.GarageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Garage bought successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Garage not found
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      security:
      - ApiKeyAuth: []
      summary: Buy Garage
      tags:
      - Garage
  /equip-car:
    put:
      consumes:
      - application/json
      description: Equip a car for a player
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Equip Car Request
        in: body
        name: equipRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Car equipped successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
      summary: Equip Car
      tags:
      - Car
  /get-all-garages:
    get:
      consumes:
      - application/json
      description: Retrieve the list of all garages
      produces:
      - application/json
      responses:
        "200":
          description: Garage list fetched successfully
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Get All Garage List
      tags:
      - Garage
  /get-garage:
    get:
      consumes:
      - application/json
      description: Retrieve the list of garages owned by a player
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Data fetched successfully
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Get Player Garage List
      tags:
      - Garage
  /guest-login:
    post:
      consumes:
      - application/json
      description: Perform guest login and generate access token
      parameters:
      - description: Guest Login Request
        in: body
        name: guestLoginRequest
        required: true
        schema:
          $ref: '#/definitions/request.GuestLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Guest Login
      tags:
      - Authentication
  /login:
    post:
      consumes:
      - application/json
      description: Perform user login and generate access token
      parameters:
      - description: Login Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: User Login
      tags:
      - Authentication
  /sell-car:
    delete:
      consumes:
      - application/json
      description: Sell a car for a player
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Sell Car Request
        in: body
        name: sellCarRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Car sold successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Car not found
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      security:
      - ApiKeyAuth: []
      summary: Sell Car
      tags:
      - Car
  /update-email:
    put:
      consumes:
      - application/json
      description: Update the email address of a player
      parameters:
      - description: Update Email Request
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/request.UpdateEmailRequest'
      - description: Access Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Email updated successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Player not found
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Update Email
      tags:
      - Player
  /upgrade-body:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: body upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade body
      tags:
      - Car
  /upgrade-engine:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Engine upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade Engine
      tags:
      - Car
  /upgrade-garage:
    put:
      consumes:
      - application/json
      description: Upgrade a player's garage to the next level
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.GarageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Garage upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade Garage
      tags:
      - Garage
  /upgrade-intake:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: intake upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade intake
      tags:
      - Car
  /upgrade-nitrous:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: nitrous upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade nitrous
      tags:
      - Car
  /upgrade-tires:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: tires upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade tires
      tags:
      - Car
  /upgrade-transmission:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: transmission upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade transmission
      tags:
      - Car
  /upgrade-turbo:
    put:
      consumes:
      - application/json
      description: Upgrade the engine of a player's car
      parameters:
      - description: Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Upgrade Request
        in: body
        name: upgradeRequest
        required: true
        schema:
          $ref: '#/definitions/request.CarUpgradesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Turbo upgraded successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Upgrade Turbo
      tags:
      - Car
swagger: "2.0"
